### ISSUE TITLE
Support for PHP 8.2

### ISSUE THREAD

**Issue by gnanakeethan** [kamilwylegala/cakephp2-php8#22]
I am planning to use this fork into a old production environment to make it compatible with some serverless initiatives. 

Can you let me know if this library already works in PHP 8.2 otherwise are there any plans to do so?

**Comment by kamilwylegala** [comment]
Hey, I tested PHP8.2 this week in dev/test environment. All good in my project,
- all tests green
- no single new deprecation notice. 

Of course in you're case it might look different, I don't use all CakePHP2's features.

I didn't proceed to production yet because I'm waiting for release of Newrelic PHP agent that will support 8.2.

**Comment by gnanakeethan** [comment]
Thanks. I checked out. It is working fine.
