### ISSUE TITLE
DEPRECATED WARNINGS ON: CORE\Cake\I18n\I18n.php

### ISSUE THREAD

**Issue by pbriongos** [kamilwylegala/cakephp2-php8#70]
[Deprecated (8192)](javascript:void(0);): Automatic conversion of false to array is deprecated [CORE\Cake\I18n\I18n.php, line 448]

[Deprecated (8192)](javascript:void(0);): Automatic conversion of false to array is deprecated [CORE\Cake\I18n\I18n.php, line 440]

Code:

`
				if ($translations !== false) {
			=>>>>		$this->_domains[$domain][$this->_lang][$this->category] = $translations;
					$this->_noLocale = false;
					break 2;
				}`

**Comment by pbarabe** [comment]
@pbriongos I see you've closed this issue as "completed". While I believe my pull request will fix it, it hasn't yet been merged so it's not actually complete yet. It's customary to leave an issue open until the fix has been fully merged into the primary branch. And in fact, GitHub will automatically close the issue since I used a "closing" keyword in the commit message. I would recommend re-opening this issue and letting GitHub's automation take care of closing it once @kamilwylegala has had a chance to do a code review and completes the pull request.

**Comment by pbriongos** [comment]
Sorry! It's my first times using github and I dont understand the basics yet. I am going to reopen it until pull request is merged.
Thanks!

**Comment by pbarabe** [comment]
@pbriongos No worries! It's all a learning opportunity, and we all start have to start somewhere :smile:, so thanks for helping out!
