### ISSUE TITLE
Security Patches

### ISSUE THREAD

**Issue by jeffpamer** [kamilwylegala/cakephp2-php8#74]
After pulling in this fork to our project, we've received dependabot alerts regarding a couple CakePHP2 vulnerabilities, notably:

```
CakePHP 2.x and 3.x before 3.1.5 might allow remote attackers to bypass the CSRF protection mechanism via the _method parameter.
```

I realize the scope of this project is to provide the minimal set of patches to meet compatibility with PHP8. But I wanted to inquire if there was any potential roadmap for patching issues like this, or if perhaps this has already been done? Thanks.

**Comment by kamilwylegala** [comment]
Hey @jeffpamer Thanks for reporting this.

I'm not aware of this issue. Could you share more details? I guess the problem was discovered after last official security patch from cakephp for version 2.10.

How `_method` can be exploited to bypass CSRF? I'd like to understand problem and plan the fix implementation.

**Comment by kamilwylegala** [comment]
Here is the patch for 3.x: https://github.com/cakephp/cakephp/commit/0f818a23a876c01429196bf7623e1e94a50230f0

It needs to be back-ported to the fork.

**Comment by MarkusBauer** [comment]
Assume you have a controller method that does not check the request method but uses POST data:
```php
public function delete() {
	// ... view data etc ...

	if (isset($this->request->data['id'])) {
		$this->Model->delete($this->request->data['id']);
		$this->Flash->success('Deleted entity');
	}
}
```

If I understand the upstream vuln correctly, then an attacker could try to send a CSRF request with method `NOTPOST` and some data. CSRF checks will not run and the request will succeed.
However, this is not so relevant today, because [modern browsers allow only GET, HEAD, and POST to be sent cross-origin](https://security.stackexchange.com/a/178563).

But backporting this patch is not too hard because most stuff in that commit is actually only refactoring unit tests. I created a PR here: https://github.com/kamilwylegala/cakephp2-php8/pull/76

**Comment by kamilwylegala** [comment]
#76 Merged.
